### ISSUE TITLE
Change validate to instance method

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/stac-task#133]
Currently, `Task.validate` is marked as a class method, but there are scenarios where having access to the task instance within the validate method would be beneficial. For example, if a STAC item property name is passed as a task parameter and we need to validate that all input items possess that property, access to `self.parameters` would be useful. What do you think about changing validate to a regular instance method?

**Comment by ircwaves** [comment]
@drnextgis -- You're thinking along these lines #147 ?  Seems reasonable to me, but is somewhat breaking-change, in that any subclasses out there which implement `validate(cls, payload)` will need to update to `validate(self)`.

**Comment by drnextgis** [comment]
Yes, @ircwaves , this is exactly what I needed!
