### ISSUE TITLE
Incorrect documentation on `collections` location in `ProcessDefinition` object

### ISSUE THREAD

**Issue by pjhartzell** [stac-utils/stac-task#17]
In several locations, the README indicates the `collections` field should be in the top-level of the `ProcessDefinition` object. However, `task.py` accesses `collections` from the `UploadOptions` object within the `ProcessDefinition` object.

The example process definition given in `task.py` shows the correct location of the `collections` field.

**Comment by ircwaves** [comment]
Good catch.  CatT (Code as the Truth).  @matthewhanson -- this wasn't part of a plan to change the ProcessDefinition structure, was it?

**Comment by matthewhanson** [comment]
@ircwaves nope, code is truth

**Comment by ircwaves** [comment]
@matthewhanson -- very nice.  And now that I've punted a strange stale corporate email address from my github account, I'll actually get notified in days not months.
