### ISSUE TITLE
move `stactask.task.Task.process` to be an identity function

### ISSUE THREAD

**Issue by ircwaves** [stac-utils/stac-task#19]
Making `stactask.task.Task.process be an identity function would cause `stac-task` to function as a sufficient downloader of `ItemCollection`s.   Also seems like a useful facility for integration/system tests of stactask.

_Originally posted by @ircwaves in https://github.com/stac-utils/stac-task/pull/18#discussion_r1166951486_

**Comment by matthewhanson** [comment]
I see the IO module here as moving into it's own repo that facilitates the downloading/uploading of assets from STAC Item metadata.

**Comment by ircwaves** [comment]
With [stac-asset](https://github.com/stac-utils/stac-asset) working as nice as it does, I think you are right that it isn't needed as a downloader.  And for my desire for an identity function for testing, that's easy enough to be a pytest fixture.
