### ISSUE TITLE
Sort stac_extensions

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-task#22]
During post processing of STAC Items (currently in the handler, when the task name and version are added), the stac_extensions should be sorted. This will ensure consistent output files that only differ in the order in which extensions were added.

**Comment by philvarner** [comment]
newer versions of pystac do this automatically for Item

**Comment by gadomski** [comment]
> newer versions of pystac do this automatically for Item

Do they? I can't find where that happens, but maybe I'm missing it.
