### ISSUE TITLE
Add option to download assets with original filename

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-task#6]
Currently stactask will download assets and name the file as the <asset_key>.<ext>, thereby keeping the extension, but possibly (probably) renaming the file.

Sometimes a subprocess will expect the file to be named the same as it was originally.   Present as option.

**Comment by ircwaves** [comment]
@matthewhanson @philvarner @gadomski  -- I'd like to motion this move from "add an option" to "make original filenames The Behavior™".  But any valid argument for `f"{asset_key}.{ext}"` file names being preferable will easily convince me otherwise.  

And yes, I've run into some external science code which depends on filenames .... again.

**Comment by matthewhanson** [comment]
This is supported by [stac-asset](https://github.com/stac-utils/stac-asset), although don't think it's the default. 
What we really need to do is drop fsspec here in favor or stac-download.

**Comment by ircwaves** [comment]
Ok, that makes sense. I'll keep a fork for immediate use, and consider #76.

**Comment by gadomski** [comment]
>  But any valid argument for f"{asset_key}.{ext}" file names being preferable will easily convince me otherwise.

I'm not sure which _should_ be the default, but one benefit of `f"{asset_key}.{ext}"` is that you're guaranteed to _not_ have name clashes when downloading all assets to a single directory (as long as you don't have duplicate dictionary keys). There's cases for both — IMO the "I just want to see what's there" use-case wants key-based, whereas the "I'm using this in a data pipeline" use-case wants orig-file-name.

**Comment by ircwaves** [comment]
> name clashes when downloading all assets to a single directory

OK, that's the trick: asset-key (or any) file naming can run amuck if `path_template` doesn't separate items out by `${id}`.  Seems like the PR may be useful until #76 can be addressed.  Incoming.
